version: '3'
services:
  todo-api:
    build: .
    image: todo-api
    ports:
      - "${TODO_API_PORT:-5000}:5000"
    volumes:
      - type: volume
        source: data
        target: /data
    env_file: .env
    environment:
      DATABASE_URL: sqlite:////data/db.sqlite
    restart: always
volumes:
  data:
